name: Build & Deploy .NET App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
          # A list of files, directories, and wildcard patterns to cache and restore
        path: ~/.nuget/packages 
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: ${{ runner.os }}-nuget
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
